### ISSUE TITLE
kak auto-pairs conflicting with lsp-auto-hover-insert-mode

### ISSUE THREAD

**Issue by JosephFerano** [ul/kak-lsp#127] opened 2018-11-10 21:14 UTC
Using `|` to signify cursor placement

 I write `my_vec|` , then press `(`, I get `my_vec(|)`. At this point, lsp does not show the hover info. It's not until I press `<space>` that it shows up, like so `my_vec( |)`. I can continue passing in arguments and the hover documentation stays active. When I disable auto-pairs, I don't have to press `<space>` and everything works as intended.

**Comment by ul** [comment] 2018-11-11 01:08
I see two the most possible scenarios:

1. `lsp_hover_insert_mode_trigger` fails because of manipulations performed by auto-pairs. You can try to tweak it in your `kakrc` that it would work with auto-pairs. If you do, please raise a PR to update default trigger 😉 which is defined here https://github.com/ul/kak-lsp/blob/master/rc/lsp.kak#L21
To test this hypothesis it should be enough to set trigger to never-failing command (`nop`?)

2. Trigger works fine, but info box is removed as a result of commands executed by auto-pairs. It could be fixed in auto-pairs to make it less intrusive (not sure how possible it is) or you can tweak `lsp-auto-hover-insert-mode-enable` to mitigate it somehow (re-trigger when `)` is inserted or something like this?). You can either extract code from `lsp-auto-hover-insert-mode-enable` into your config under the new name or override it with `-override` switch of `define-command`.

**Comment by maximbaz** [comment] 2018-11-11 01:33
I think the problem is with trigger, it is easy to test it manually:

Cursor is []:

```
my_vec([]
```

Executing `<a-f>(s\A[^)]+\z<ret>` doesn't fail

```
my_vec([)]
```

Executing `<a-f>(s\A[^)]+\z<ret>` fails because there are no `non-)` chars after `(`.

**Closed** 2018-11-24 11:33 UTC
