### ISSUE TITLE
5000 process of kak-lsp

### ISSUE THREAD

**Issue by shrit** [ul/kak-lsp#271] opened 2019-12-27 13:52 UTC
I left kakoune running during the night. Today, checking the `htop` for memory, I have noticed at least 5000 processes of `kak-lsp`
Here is a screenshot of a part of these processes.
Best regards,
![2019-12-27-123519_1366x768_scrot](https://user-images.githubusercontent.com/15039782/71519570-6877da00-28b8-11ea-9c94-72dbf2a11116.png)

**Comment by topisani** [comment] 2019-12-27 14:44
Could you get the actual full command field for one of those?

**Comment by shrit** [comment] 2019-12-28 12:25
![2019-12-28-131949_1366x768_scrot](https://user-images.githubusercontent.com/15039782/71543630-78092880-2975-11ea-8858-352eb17c5989.png)
![2019-12-28-132014_1366x768_scrot](https://user-images.githubusercontent.com/15039782/71543635-88b99e80-2975-11ea-9eb9-5413f3b3840a.png)

**Comment by topisani** [comment] 2019-12-28 12:36
And this just builds up over time? i.e., it's not just suddenly launching all of these in a loop?

For some reason, the processes (which should be launched) don't exit.

I can't seem to reproduce this. Which language server are you using, and do you get hover messages?

**Comment by shrit** [comment] 2019-12-28 12:38
It is building over time.
What do you mean by language server and hover messages ?

**Comment by topisani** [comment] 2019-12-28 12:40
which language are you using `kak-lsp` with? and which language server do you use for it?

The hover messages are the `info` box popups with documentation/type information about the thing your cursor is at.

**Comment by shrit** [comment] 2019-12-28 13:03
Well, I started using kakoune a week ago, so I am not expert yet.
I am using these kak-lsp configurations: 
https://github.com/andreyorst/dotfiles/blob/8270ea435a4ebbdca137660616aaa7fd49b13a65/.config/kak/plugins.kak#L78-L118
I am writing code mainly in C++.

**Comment by shrit** [comment] 2019-12-28 13:21
My bad, I forgot to create a kak-lsp configurations file in .config/kak-lsp.
I will keep open just to be sure that it is resolved

**Comment by topisani** [comment] 2019-12-28 13:28
That might be it.

By the way, for C++, I'd probably recommend using `clangd` instead of `cquery`. I'll consider changing the default, since clangd is also usually easier to install, and, for me at least, a lot faster.

You're probably gonna want a `clangd` from clang 9, and then something like this in your `kak-lsp.toml`:

```toml
[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".ccls"]
command = "clangd"
args = ['--suggest-missing-includes']
```

**Comment by shrit** [comment] 2020-01-02 22:02
I think we can close this issue now.
However, I am getting always a message error when I am in normal mode: invalid-AST?
Why this message is shown? it will disappear when I get into insert mode

**Comment by ul** [comment] 2020-01-24 21:56
This message is returned by cquery. To find out what request provokes it you may try to enable debug logs https://github.com/ul/kak-lsp#troubleshooting

kak-lsp should work without config file as it has default config embedded into it. This is definitely a bug, I’ll look into it.

**Comment by ul** [comment] 2020-01-24 22:14
I struggle to reproduce it, on macOS kak-lsp starts successfully with just embedded config. I wonder what exactly happens in your environment.

**Comment by ul** [comment] 2020-01-24 22:17
I’m going to close this issue for now. If you are keen to spend time on investigation of no-config case please let me know by opening a new issue with the debug log for hung up kak-lsp instances.

**Closed by ul** 2020-01-24 22:17 UTC
